import { test } from "node:test";
import assert from "node:assert";
import { parseBackupDate } from "../src/features/admin/utils/backup";

test("GFS Backup Filename Date Parsing", () => {
  // Let's mock a filename with the timestamp format generated by runVacuumBackup:
  // timestamp format is: new Date().toISOString().replace(/[:.]/g, "-")
  // e.g. "backup-2026-05-21T15-47-22-123Z.db"
  const timestamp = "2026-05-21T15-47-22-123Z";
  const filename = `backup-${timestamp}.db`;
  
  const parsedDate: Date = parseBackupDate(filename);
  
  assert.ok(!isNaN(parsedDate.getTime()), "Parsed date should be a valid Date object");
  assert.strictEqual(parsedDate.getUTCFullYear(), 2026);
  assert.strictEqual(parsedDate.getUTCMonth(), 4); // 0-indexed (May is 4)
  assert.strictEqual(parsedDate.getUTCDate(), 21);
  assert.strictEqual(parsedDate.getUTCHours(), 15);
  assert.strictEqual(parsedDate.getUTCMinutes(), 47);
  assert.strictEqual(parsedDate.getUTCSeconds(), 22);
  assert.strictEqual(parsedDate.getUTCMilliseconds(), 123);
});
